### ISSUE TITLE
Sorry for doing this. I need help from you

### ISSUE THREAD

**Issue by infahash** [rockz5555/NFG-Multi-Crack#1]
Hello @rockz5555. I found you form apk you have edited. - CinemaHD_1.3.3.

I've tried to edit original CINEMA app and It's showing only blank screen after recompile. After trying few times I was able to get into the main screen but showing mask image without movies. After serching more on it I found something happen with backend when opening app for first time. I tried to capture network communication but not success because it's using ssl v3 security.

No anymore time waste. I need to find the way to bypass this ssl v3 security. I found it on few apps and nothing work after recompiling. So I appreciate any help from you.

Thanks!

**Comment by rockz5555** [comment]
Hey mate,

As I remember machan, I  haven't touch  **CinemaHD** app. Maybe someone else. Coz, some dudes are using my version of apktool with my signature on it. Apart from that, oya app eka mata break karannada machan kiyanne?

**Comment by infahash** [comment]
Ammata siri uba lankawenda?

**Comment by infahash** [comment]
Whatsapp 0776749248 plz

**Comment by infahash** [comment]
Mata oni me ssl v3 use karana app break karanna method ekak hoya ganna. Mulinma try kale snapchat. Eka hari giye nathi nisa wena app try kala. Still no success.

**Comment by infahash** [comment]
Sorry bro. Number eka waradila. 0776749148
