### ISSUE TITLE
BitAim Not Showing Up, Using SEP|11|2022 Update

### ISSUE THREAD

**Issue by George-Seven** [rockz5555/NFG-Multi-Crack#11]
Hello, sorry for the inconvenience if I might be mistaken.

I have updated hooks to SEP|11|2022 and downloaded BitAim + from [official](https://bitaimplus.com/download.html) but it is not showing up in main screen.

Please need your advice.

**Comment by rockz5555** [comment]
Hey mate,

NFG support this package name,

`app.ai.lab.eightballaim`

Please check yours

**Comment by George-Seven** [comment]
Thanks for the the speedy response. Can you please give me a link that apk.

Thanks again.

**Comment by rockz5555** [comment]
Hey bud, it's the official link you've provided in OP,

`https://www.tptrb.com/download.html`

Make sure to download the _Link 2_

**Comment by rockz5555** [comment]
Hey bud,

Use this link,

[Download](https://www.tptrb.com/)

**Comment by George-Seven** [comment]
Yes, it is showing now, thank you.

Edit - It is hooking without error, but when press start button in the app, it just pauses like button doesn't exist... unhooking and watching ads for free users model works so I think it has protection...

**Comment by George-Seven** [comment]
The new SEP|26|2022 update has fixed this. Thanks!
