### ISSUE TITLE
damn on u

### ISSUE THREAD

**Issue by Hamood111** [rockz5555/NFG-Multi-Crack#17]
I'm on Android 12 I'm using magisk 26.1 don't have a lot of modules or apps only basics so why the fuck this app is crashing even the telegram group nobody have answers everyone have the same shitty problem  even Google and banking apps are working why the fuck nfg crack tool is crashing I hope you fix it very soon or delete the fucking annoying project

**Comment by rockz5555** [comment]
Did anybody force you to use NFG? Or ask you to make any payments? Hell no!!

If you're unsatisfied, just get the FO!!!
